apiVersion: v1
kind: Service
metadata:
  name: sfe-devops-app-service
spec:
  selector:
    app: sfe-devops-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  type: LoadBalancer